// lib/data.ts — Mock data for Phase 1 (zero cost, no database needed)

export const INDIAN_STATES = [
  "Maharashtra",
  "Karnataka",
  "Delhi",
  "Telangana",
  "Gujarat",
  "Tamil Nadu"
];

export const STATS = [
  { label: "Members", value: 10000, suffix: "+" },
  { label: "Events Run", value: 64, suffix: "+" },
  { label: "Cities Reached", value: 8, suffix: "" },
  { label: "Partners", value: 24, suffix: "+" },
];

export const EVENTS = [
  {
    id: "1",
    slug: "mumbai-ai-builders-meetup-oct-2026",
    title: "Mumbai AI Builders Meetup",
    type: "meetup" as const,
    date: "2026-10-18T18:00:00",
    venue: "WeWork BKC, Bandra",
    state: "Maharashtra",
    description: "A hands-on evening where Mumbai's AI builders demo projects, share learnings, and find collaborators. Open to all levels — bring your laptop and your ideas.",
    tags: ["AI", "Machine Learning", "Networking"],
    capacity: 120,
    rsvpCount: 87,
    image: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600&auto=format&fit=crop&q=80",
    featured: true,
  },
  {
    id: "2",
    slug: "hack-mumbai-2026",
    title: "HackMumbai 2026",
    type: "hackathon" as const,
    date: "2026-11-08T09:00:00",
    venue: "T-Hub Mumbai, Powai",
    state: "Maharashtra",
    description: "Mumbai's biggest 24-hour hackathon. Build products that solve real Mumbai city problems. ₹3L+ in prizes. Team up, ship fast, win big.",
    tags: ["Hackathon", "Web3", "Civic Tech"],
    capacity: 300,
    rsvpCount: 214,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&auto=format&fit=crop&q=80",
    featured: true,
  },
  {
    id: "3",
    slug: "open-source-workshop-sept-2026",
    title: "Open Source Contribution Workshop",
    type: "workshop" as const,
    date: "2026-10-05T10:00:00",
    venue: "Google for Startups Campus, Andheri",
    state: "Maharashtra",
    description: "New to open source? This workshop walks you through making your first PR, reading codebases, and getting started with top Indian open source projects.",
    tags: ["Open Source", "Git", "Beginners"],
    capacity: 60,
    rsvpCount: 58,
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&auto=format&fit=crop&q=80",
    featured: false,
  },
  {
    id: "4",
    slug: "founders-fireside-andheri",
    title: "Founders Fireside — Andheri Edition",
    type: "meetup" as const,
    date: "2026-10-25T19:00:00",
    venue: "Innov8 Coworking, Andheri",
    state: "Maharashtra",
    description: "An intimate conversation with 3 Mumbai startup founders. Revenue journeys, hiring mistakes, and honest advice. Limited to 40 seats.",
    tags: ["Startups", "Founders", "Networking"],
    capacity: 40,
    rsvpCount: 31,
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=600&auto=format&fit=crop&q=80",
    featured: false,
  },
  {
    id: "5",
    slug: "blr-web3-builders",
    title: "Bangalore Web3 Builders",
    type: "meetup" as const,
    date: "2026-10-22T17:00:00",
    venue: "Draper Startup House, Koramangala",
    state: "Karnataka",
    description: "Meet the top builders in the Bangalore Web3 ecosystem. Demo day and networking mixer.",
    tags: ["Web3", "Crypto", "Networking"],
    capacity: 100,
    rsvpCount: 95,
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80",
    featured: false,
  },
  {
    id: "6",
    slug: "delhi-ncr-saas-mixer",
    title: "Delhi NCR SaaS Mixer",
    type: "meetup" as const,
    date: "2026-11-02T18:30:00",
    venue: "Cyber Hub, Gurugram",
    state: "Delhi",
    description: "An exclusive invite-only mixer for SaaS founders and engineers in the Delhi NCR region.",
    tags: ["SaaS", "Founders", "Mixer"],
    capacity: 50,
    rsvpCount: 48,
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&auto=format&fit=crop&q=80",
    featured: false,
  },
  {
    id: "7",
    slug: "hyderabad-dev-fest",
    title: "Hyderabad DevFest 2026",
    type: "hackathon" as const,
    date: "2026-11-15T10:00:00",
    venue: "HITEC City, Hyderabad",
    state: "Telangana",
    description: "The largest developer festival in Telangana. Cloud, AI, and Mobile tracks.",
    tags: ["Cloud", "AI", "Mobile"],
    capacity: 500,
    rsvpCount: 420,
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&auto=format&fit=crop&q=80",
    featured: true,
  }
];

export const OPPORTUNITIES = [
  {
    id: "1",
    type: "job" as const,
    title: "Senior Frontend Engineer",
    company: "Razorpay",
    location: "Mumbai (Hybrid)",
    domain: "Fintech",
    tags: ["React", "TypeScript", "Next.js"],
    applyUrl: "https://razorpay.com/jobs",
    deadline: "2026-10-30",
    posted: "2026-09-10",
  },
  {
    id: "2",
    type: "internship" as const,
    title: "Product Design Intern",
    company: "Zepto",
    location: "Mumbai",
    domain: "E-commerce",
    tags: ["Figma", "UX Research", "Prototyping"],
    applyUrl: "#",
    deadline: "2026-10-15",
    posted: "2026-09-08",
  },
  {
    id: "3",
    type: "job" as const,
    title: "Backend Engineer — Node.js",
    company: "CRED",
    location: "Mumbai / Remote",
    domain: "Fintech",
    tags: ["Node.js", "PostgreSQL", "AWS"],
    applyUrl: "#",
    deadline: "2026-11-01",
    posted: "2026-09-12",
  },
  {
    id: "4",
    type: "internship" as const,
    title: "Data Science Intern",
    company: "PharmEasy",
    location: "Mumbai",
    domain: "Healthtech",
    tags: ["Python", "ML", "Data Analysis"],
    applyUrl: "#",
    deadline: "2026-10-20",
    posted: "2026-09-09",
  },
  {
    id: "5",
    type: "job" as const,
    title: "DevOps Engineer",
    company: "Navi Technologies",
    location: "Mumbai",
    domain: "Fintech",
    tags: ["Kubernetes", "AWS", "CI/CD"],
    applyUrl: "#",
    deadline: "2026-10-28",
    posted: "2026-09-11",
  },
  {
    id: "6",
    type: "job" as const,
    title: "Full-Stack Developer",
    company: "Meesho",
    location: "Mumbai / Remote",
    domain: "E-commerce",
    tags: ["React", "Go", "Microservices"],
    applyUrl: "#",
    deadline: "2026-11-05",
    posted: "2026-09-12",
  },
];

export const PARTNERS = [
  { name: "Sponsor 1", logo: "/logos/orig1.png" },
  { name: "Sponsor 2", logo: "/logos/orig2.png" },
  { name: "Sponsor 3", logo: "/logos/orig3.png" },
  { name: "Sponsor 4", logo: "/logos/orig4.png" },
  { name: "Sponsor 5", logo: "/logos/orig5.png" },
  { name: "Hack2Skill", logo: "/logos/hack2skill.png" },
  { name: "HackerEarth", logo: "/logos/hackerearth.png" },
  { name: "Ignite Room", logo: "/logos/ignite.jpeg" },
  { name: "Google Developers", logo: "/logos/google-dev.png" },
];

export const TESTIMONIALS = [
  {
    quote: "MTC is where I found my co-founder. We met at the AI Builders meetup, formed a team at HackMumbai, and now we're building together full-time.",
    name: "Priya Nair",
    role: "Co-Founder",
    company: "Fynzo AI",
    avatar: "PN",
  },
  {
    quote: "Every event I've attended has been absurdly well-curated. No fluff, no generic talks — just people doing real work sharing real knowledge.",
    name: "Arjun Mehta",
    role: "Senior Engineer",
    company: "Razorpay",
    avatar: "AM",
  },
  {
    quote: "I got my first internship through MTC's opportunities board. Joined as a student, now I mentor others at our weekly sessions.",
    name: "Sneha Rao",
    role: "Product Designer",
    company: "Zepto",
    avatar: "SR",
  },
  {
    quote: "The speaker directory is a game-changer. We found our workshop speakers in hours instead of weeks. Will definitely partner again.",
    name: "Karan Shah",
    role: "Community Lead",
    company: "GFG Mumbai",
    avatar: "KS",
  },
];


export const NEXT_EVENT = EVENTS.find(e => e.featured) || EVENTS[0];

export const GALLERY_PHOTOS = [
  { id: 1, src: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&auto=format&fit=crop&q=80", alt: "HackMumbai 24H Hackathon Finals" },
  { id: 2, src: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600&auto=format&fit=crop&q=80", alt: "AI Builders Keynote Session" },
  { id: 3, src: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=600&auto=format&fit=crop&q=80", alt: "Founders Fireside Chat" },
  { id: 4, src: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&auto=format&fit=crop&q=80", alt: "Team Collaboration & Mentoring" },
  { id: 5, src: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&auto=format&fit=crop&q=80", alt: "Tech Architecture Panel" },
  { id: 6, src: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&auto=format&fit=crop&q=80", alt: "Mumbai Open Source Workshop" },
  { id: 7, src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&auto=format&fit=crop&q=80", alt: "Code Sprint & Live Demos" },
  { id: 8, src: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80", alt: "Project Demo Stage Pitch" },
  { id: 9, src: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&auto=format&fit=crop&q=80", alt: "Audience at Main Auditorium" },
  { id: 10, src: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&auto=format&fit=crop&q=80", alt: "Tech Speaker Q&A" },
  { id: 11, src: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600&auto=format&fit=crop&q=80", alt: "Product Design Review Session" },
  { id: 12, src: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600&auto=format&fit=crop&q=80", alt: "Award Ceremony & Trophies" },
];
